# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='axisdate',
            fields=[
                ('AXD', models.DateField(primary_key=True, serialize=False, verbose_name='日期')),
                ('WK', models.IntegerField(verbose_name='星期')),
                ('MON', models.IntegerField(verbose_name='月份')),
                ('YEA', models.IntegerField(verbose_name='年份')),
            ],
            options={
                'verbose_name': '1305日期轴',
                'verbose_name_plural': '1305日期轴',
            },
        ),
        migrations.CreateModel(
            name='axistime',
            fields=[
                ('AXT', models.TimeField(primary_key=True, serialize=False, verbose_name='时间')),
                ('TT', models.CharField(blank=True, max_length=20, null=True, verbose_name='时间类型')),
            ],
            options={
                'verbose_name': '1306时间轴',
                'verbose_name_plural': '1306时间轴',
            },
        ),
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('code', models.CharField(help_text='设置前后1年工作日历。', max_length=40, primary_key=True, serialize=False, verbose_name='日历编码')),
                ('cdescription', models.TextField(blank=True, help_text='筛选出各节假日休息日，其它日期默认为工作日。', null=True, verbose_name='说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('cdate', models.ManyToManyField(to='p_admin.axisdate', verbose_name='日期')),
            ],
            options={
                'verbose_name': '1307日历设置',
                'verbose_name_plural': '1307日历设置',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='部门代码')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='部门名称')),
                ('category', models.CharField(choices=[('0', '公司集团'), ('1', '工厂'), ('2', '事业部'), ('3', '职能部门'), ('4', '作业单位'), ('P', '生产线'), ('C', 'Cell')], max_length=40, verbose_name='部门类别')),
                ('createdate', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '1301部门组织',
                'verbose_name_plural': '1301部门组织',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='模组代码')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='模组名称')),
                ('url', models.CharField(blank=True, max_length=120, null=True, verbose_name='模组路径')),
                ('icon', models.CharField(blank=True, max_length=120, null=True, verbose_name='图标')),
                ('level', models.SmallIntegerField(choices=[(0, '系统'), (1, '子系统'), (2, '模组'), (3, '次级模组'), (4, '功能'), (5, '次级功能'), (6, '对像')], default=2, verbose_name='层级')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='模组分配给角色')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='p_admin.module', verbose_name='上级模组')),
            ],
            options={
                'verbose_name': '1303系统模组',
                'verbose_name_plural': '1303系统模组',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('jn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('ondate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='到职日期')),
                ('title', models.CharField(blank=True, choices=[('1', '职员'), ('2', '作业员'), ('3', '工程师'), ('4', '组长'), ('5', '主管'), ('6', '经理'), ('7', '总监'), ('8', '副总经理'), ('9', '总经理')], max_length=40, null=True, verbose_name='职务')),
                ('states', models.BooleanField(default=1, verbose_name='在职状态')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deporganization', to='p_admin.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '1302组织人员',
                'verbose_name_plural': '1302组织人员',
                'ordering': ['dep', 'jn'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('telphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='手机')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('department', models.ManyToManyField(blank=True, null=True, related_name='deps', to='p_admin.department', verbose_name='管理部门')),
                ('module', models.ManyToManyField(blank=True, null=True, related_name='mds', to='p_admin.module', verbose_name='管理模组')),
                ('onwer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='onwers', to='p_admin.department', verbose_name='直属部门')),
            ],
            options={
                'verbose_name': '1304个人设置',
                'verbose_name_plural': '1304个人设置',
            },
        ),
        migrations.CreateModel(
            name='ProjectGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_admin.module')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_admin.module')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('code', models.CharField(help_text='依据各部门上下班时间不同设置。', max_length=40, primary_key=True, serialize=False, verbose_name='班表编码')),
                ('tdescription', models.TextField(blank=True, help_text='筛选出各段工作时间，其余时间默认为休息状态。', null=True, verbose_name='说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('ctime', models.ManyToManyField(to='p_admin.axistime', verbose_name='时间')),
            ],
            options={
                'verbose_name': '1308班表设置',
                'verbose_name_plural': '1308班表设置',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='jn',
            field=models.ManyToManyField(blank=True, to='p_admin.organization', verbose_name='直属人员'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='p_admin.department', verbose_name='上级部门'),
        ),
        migrations.AddField(
            model_name='department',
            name='responsibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='权责主管'),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='projectgroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
    ]
