# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_pdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CELLHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingdate', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('PL', models.CharField(max_length=40, verbose_name='部门')),
                ('cell', models.CharField(max_length=40, verbose_name='Cell')),
                ('members', models.SmallIntegerField(default=1, verbose_name='出勤人数')),
                ('workinghours', models.DecimalField(decimal_places=2, default=8, max_digits=8, verbose_name='出勤工时')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '113总工时',
                'verbose_name_plural': '113总工时',
            },
        ),
        migrations.CreateModel(
            name='dispatch',
            fields=[
                ('dpid', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='派工码')),
                ('PL', models.CharField(max_length=40, null=True, verbose_name='部门')),
                ('cell', models.CharField(max_length=40, null=True, verbose_name='Cell')),
                ('operation', models.CharField(max_length=40, null=True, verbose_name='工站')),
                ('po', models.CharField(max_length=40, null=True, verbose_name='订单')),
                ('poid', models.CharField(blank=True, max_length=40, null=True, verbose_name='订单项次')),
                ('item', models.CharField(max_length=40, null=True, verbose_name='料号')),
                ('wo', models.CharField(max_length=40, null=True, verbose_name='工单')),
                ('startqty', models.SmallIntegerField(default=1, verbose_name='派工数量')),
                ('completeqty', models.SmallIntegerField(default=0, verbose_name='完工数量')),
                ('startdate', models.DateField(default=django.utils.timezone.now, verbose_name='开工日期')),
                ('completedate', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('states', models.SmallIntegerField(default='1', help_text='1:正常派单，2：返工派单, 99：生产完工，0：取消派单', verbose_name='状态码')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '101生产派工',
                'verbose_name_plural': '101生产派工',
            },
        ),
        migrations.CreateModel(
            name='dispatchbom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=80, verbose_name='工单材料')),
                ('qty', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='用料数量')),
                ('lot', models.TextField(blank=True, null=True, verbose_name='用料信息')),
                ('states', models.SmallIntegerField(default='1', help_text='1:待制，2：在制，3：待检，99:关闭,0：取消', verbose_name='状态码')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchbom', to='p_sfm.dispatch', verbose_name='派工码')),
            ],
            options={
                'verbose_name': '104工单用料',
                'verbose_name_plural': '104工单用料',
            },
        ),
        migrations.CreateModel(
            name='dispatchrouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField(default=1, verbose_name='作业顺序')),
                ('states', models.TextField(default='1', null=True, verbose_name='流程状态说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchrouting', to='p_sfm.dispatch', verbose_name='派工码')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatchroutingprocess', to='p_pdm.pcode', verbose_name='生产制程')),
            ],
            options={
                'verbose_name': '103派工制程',
                'verbose_name_plural': '103派工制程',
            },
        ),
        migrations.CreateModel(
            name='dispatchsn',
            fields=[
                ('sn', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='识别序号')),
                ('lotsize', models.SmallIntegerField(default=1, verbose_name='批量大小')),
                ('states', models.SmallIntegerField(default='1', help_text='1:首次派发，>=2：多次派发，0：取消', verbose_name='派单状态')),
                ('dispatch', models.CharField(help_text='移转后更新', max_length=200, null=True, verbose_name='当前工序')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchsn', to='p_sfm.dispatch', verbose_name='派工码')),
            ],
            options={
                'verbose_name': '102派工序号',
                'verbose_name_plural': '102派工序号',
            },
        ),
        migrations.CreateModel(
            name='modelfail',
            fields=[
                ('failcode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='不良代码')),
                ('faildesc', models.TextField(null=True, verbose_name='不良说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operation', models.ForeignKey(blank=True, limit_choices_to=models.Q(category='2'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='failmodeoperation', to='p_pdm.operation', verbose_name='工作中心')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='failmodeproducttree', to='p_pdm.producttree', verbose_name='产品群')),
                ('responder', models.ForeignKey(blank=True, help_text='选择人员后，发生此项异常时，系统自动通知回应者', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PLFMResponderuser', to=settings.AUTH_USER_MODEL, verbose_name='回应者')),
            ],
            options={
                'verbose_name': '108不良代码',
                'verbose_name_plural': '108不良代码',
            },
        ),
        migrations.CreateModel(
            name='modelqc',
            fields=[
                ('qccode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='缺失代码')),
                ('qcdesc', models.TextField(null=True, verbose_name='缺失说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operation', models.ForeignKey(blank=True, limit_choices_to=models.Q(category='2'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Qoperation', to='p_pdm.operation', verbose_name='工作中心')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Qproducttree', to='p_pdm.producttree', verbose_name='产品群')),
                ('responder', models.ForeignKey(blank=True, help_text='选择人员后，发生此项异常时，系统自动通知回应者', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FQCFMResponderuser', to=settings.AUTH_USER_MODEL, verbose_name='回应者')),
            ],
            options={
                'verbose_name': '110缺失代码',
                'verbose_name_plural': '110缺失代码',
            },
        ),
        migrations.CreateModel(
            name='productsn',
            fields=[
                ('prsn', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='产品序号')),
                ('lotsize', models.DecimalField(decimal_places=0, default=1, max_digits=8, verbose_name='产品数量')),
                ('states', models.SmallIntegerField(default='0', help_text='0:制程中，1：完工入库，99：已出货，-1：成品退回', verbose_name='状态码')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingsn', to='p_sfm.dispatchsn', verbose_name='识别序号')),
            ],
            options={
                'verbose_name': '112出货序号',
                'verbose_name_plural': '112出货序号',
                'ordering': ['trsn', 'prsn'],
            },
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('trid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='追溯码')),
                ('workingdate', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('PL', models.CharField(max_length=40, verbose_name='部门')),
                ('cell', models.CharField(max_length=40, verbose_name='Cell')),
                ('operation', models.CharField(max_length=40, verbose_name='完工工站')),
                ('groups', models.CharField(max_length=40, null=True, verbose_name='群组')),
                ('po', models.CharField(max_length=40, null=True, verbose_name='订单')),
                ('poid', models.CharField(max_length=40, null=True, verbose_name='订单项次')),
                ('item', models.CharField(max_length=40, null=True, verbose_name='料号')),
                ('wo', models.CharField(max_length=40, null=True, verbose_name='工单')),
                ('passqty', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Pass数量')),
                ('failqty', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fail数量')),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('completetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成时间')),
                ('states', models.SmallIntegerField(choices=[('0', '未完工'), ('1', '完工待检'), ('99', '检验合格'), ('-1', '批失效')], default=1, editable=False, verbose_name='状态码')),
                ('operatorlist', models.TextField(blank=True, null=True, verbose_name='人员名单')),
                ('processlist', models.TextField(blank=True, null=True, verbose_name='制程明细')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='移转说明')),
            ],
            options={
                'verbose_name': '105生产移转',
                'verbose_name_plural': '105生产移转',
                'ordering': ['workingdate', 'PL', 'cell', 'operation'],
            },
        ),
        migrations.CreateModel(
            name='transferfail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=40, null=True, verbose_name='识别序号')),
                ('failcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='不良代码')),
                ('failqty', models.SmallIntegerField(default=1, verbose_name='不良数量')),
                ('faildesc', models.TextField(blank=True, null=True, verbose_name='不良说明')),
                ('states', models.CharField(choices=[('1', '待检'), ('2', '返工'), ('3', '回收'), ('4', '其它'), ('0', '取消记录')], default=1, max_length=40, verbose_name='处置状态')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faildetail', to='p_sfm.transfer', verbose_name='追溯码')),
            ],
            options={
                'verbose_name': '109不良记录',
                'verbose_name_plural': '109不良记录',
            },
        ),
        migrations.CreateModel(
            name='transferparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=40, null=True, verbose_name='识别序号')),
                ('parameter', models.CharField(max_length=40, verbose_name='参数')),
                ('pvalue', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数值')),
                ('pdesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='记录描述')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processparameter', to='p_sfm.transfer', verbose_name='追溯码')),
            ],
            options={
                'verbose_name': '115制程参数记录',
                'verbose_name_plural': '115制程参数记录',
            },
        ),
        migrations.CreateModel(
            name='transferqc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeqty', models.SmallIntegerField(verbose_name='送检数量')),
                ('qcqty', models.SmallIntegerField(verbose_name='检验数量')),
                ('failqty', models.SmallIntegerField(verbose_name='缺失数量')),
                ('qccode', models.CharField(max_length=40, verbose_name='缺失代码')),
                ('qcdesc', models.TextField(blank=True, null=True, verbose_name='检验说明')),
                ('result', models.CharField(choices=[('1', '合格'), ('2', '条件充收'), ('-1', '批退')], default=1, max_length=40, verbose_name='结果判定')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fqcdetail', to='p_sfm.transfer', verbose_name='追溯码')),
            ],
            options={
                'verbose_name': '111FQC记录',
                'verbose_name_plural': '111FQC记录',
            },
        ),
        migrations.CreateModel(
            name='transfersn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=40, verbose_name='识别序号')),
                ('passqty', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='良品数量')),
                ('failqty', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='失效数量')),
                ('operation', models.CharField(max_length=40, null=True, verbose_name='转入工站')),
                ('operator', models.TextField(null=True, verbose_name='作业人员')),
                ('states', models.CharField(default='1', help_text='与派单状态相同', max_length=40, verbose_name='状态')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='p_sfm.transfer', verbose_name='追溯码')),
            ],
            options={
                'verbose_name': '106移转序号',
                'verbose_name_plural': '106移转序号',
            },
        ),
        migrations.CreateModel(
            name='transfertracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=40, verbose_name='材料品号')),
                ('lot', models.CharField(blank=True, max_length=120, null=True, verbose_name='材料批号')),
                ('failqty', models.CharField(blank=True, default='0', help_text='材料不良情况为损耗，正常损耗=0.', max_length=40, null=True, verbose_name='损耗数')),
                ('faildesc', models.TextField(blank=True, null=True, verbose_name='损耗说明')),
                ('states', models.SmallIntegerField(choices=[('1', '待检'), ('2', '退换料'), ('3', '报废'), ('4', '回收'), ('5', '其它'), ('0', '取消记录')], default='1', help_text='1:待检，2：退换料，3：报废，4: 回收,0：取消记录', verbose_name='处理状态')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('trid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='p_sfm.transfer', verbose_name='追溯码')),
            ],
            options={
                'verbose_name': '107用料记录',
                'verbose_name_plural': '107用料记录',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transfersn',
            unique_together={('trid', 'sn')},
        ),
        migrations.AlterUniqueTogether(
            name='dispatchrouting',
            unique_together={('dpid', 'process', 'step')},
        ),
        migrations.AlterUniqueTogether(
            name='dispatchbom',
            unique_together={('dpid', 'component')},
        ),
    ]
