# Generated by Django 2.0.4 on 2018-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsn',
            name='states',
            field=models.SmallIntegerField(default='1', help_text='1:制程中，9：完工入库，99：已出货，-1：成品退回', verbose_name='状态码'),
        ),
    ]
