# Generated by Django 2.0.4 on 2018-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sfm', '0002_auto_20180712_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchsn',
            name='states',
            field=models.SmallIntegerField(default='1', help_text='1:首次派发，>=2：多次派发，0：拆解流程单', verbose_name='派单状态'),
        ),
    ]
