# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcode', models.CharField(max_length=40, verbose_name='目标项目')),
                ('tvalue', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='目标值')),
                ('tucl', models.DecimalField(decimal_places=2, default=1.25, max_digits=12, verbose_name='上限')),
                ('tlcl', models.DecimalField(decimal_places=2, default=0.75, max_digits=12, verbose_name='下限')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updatename', models.CharField(blank=True, max_length=40, verbose_name='添加者')),
                ('dep', models.ForeignKey(limit_choices_to=models.Q(('category', 'P'), ('category', 'C'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='p_admin.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '001看板目标',
                'verbose_name_plural': '001看板目标',
                'ordering': ['dep', 'tcode'],
            },
        ),
        migrations.CreateModel(
            name='SumReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkingDate', models.DateField(verbose_name='工作日期')),
                ('PL', models.CharField(max_length=80, null=True, verbose_name='部门')),
                ('Cell', models.CharField(max_length=80, null=True, verbose_name='Cell')),
                ('Operation', models.CharField(max_length=80, null=True, verbose_name='工站')),
                ('MPSQty', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='计划完工数')),
                ('CompleteQty', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='实际完工数')),
                ('PQ', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='人数')),
                ('OutputHR', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='完工工时')),
                ('ATH', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='出勤工时')),
                ('NWK', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='无效工时')),
                ('URT', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='工时利用率')),
                ('Efficiency', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='作业效率')),
                ('Productivity', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='综合生产力')),
                ('AchievingRate', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='交期达率')),
                ('StandardProductQty', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='标准完工数')),
                ('Members', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='计划人数')),
                ('WorkingHours', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='计划工时')),
                ('UPPH', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='人均小时产出')),
                ('Item', models.TextField(null=True, verbose_name='无效项目')),
                ('PPM', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='百万分之')),
                ('FCY', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='直通率')),
            ],
            options={
                'verbose_name': '002MES报表',
                'verbose_name_plural': '002MES报表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='deptarget',
            unique_together={('dep', 'tcode')},
        ),
    ]
