# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfqdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=40, null=True, verbose_name='分类1')),
                ('category2', models.CharField(max_length=40, null=True, verbose_name='分类2')),
                ('category3', models.CharField(max_length=40, null=True, verbose_name='分类3')),
                ('item', models.CharField(max_length=40, verbose_name='料号')),
                ('R', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='时间')),
                ('F', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='频率')),
                ('Q', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('M', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('RG', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='时间分组')),
                ('FG', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='频率分组')),
                ('QG', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='数量分组')),
                ('MG', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='金额分组')),
                ('rfq', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='RFQ')),
                ('rfm', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='RFM')),
            ],
            options={
                'verbose_name': '502RFQ数据',
                'verbose_name_plural': '502RFQ数据',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='rfqgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R', '时间'), ('F', '频率'), ('Q', '数量'), ('M', '金额')], max_length=40, verbose_name='分类')),
                ('group', models.CharField(choices=[('0.01', '1'), ('0.1', '2'), ('1.0', '3'), ('2.0', '4'), ('3.0', '5'), ('4.0', '6'), ('5.0', '7')], max_length=40, verbose_name='分组')),
                ('groupvalue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='组值')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '501RFM分组',
                'verbose_name_plural': '501RFM分组',
                'ordering': ['category', 'group'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rfqgroup',
            unique_together={('category', 'group')},
        ),
    ]
