# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bomport',
            fields=[
                ('item', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='料号')),
                ('port', models.SmallIntegerField(default=1, verbose_name='接头数')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '213产品头数',
                'verbose_name_plural': '213产品头数',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('item', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='产品号(组)')),
                ('states', models.BooleanField(default='1', verbose_name='状态')),
                ('itemdesc', models.TextField(verbose_name='产品描述')),
                ('itemspec', models.TextField(verbose_name='产品规格')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '203产品组',
                'verbose_name_plural': '203产品组',
                'ordering': ['productgroup', 'item'],
            },
        ),
        migrations.CreateModel(
            name='itembom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=80, verbose_name='主件')),
                ('seq', models.SmallIntegerField(verbose_name='序号')),
                ('component', models.CharField(max_length=80, verbose_name='零件')),
                ('componentdesc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('componentspec', models.TextField(blank=True, null=True, verbose_name='规格')),
                ('qty', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='用料数量')),
                ('loss', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='损耗量')),
                ('units', models.CharField(default='PCS', max_length=40, verbose_name='用料单位')),
                ('starttime', models.DateField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('endtime', models.DateField(blank=True, null=True, verbose_name='失效时间')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '212产品用料',
                'verbose_name_plural': '212产品用料',
                'ordering': ['item', 'component'],
            },
        ),
        migrations.CreateModel(
            name='itemparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40, verbose_name='产品')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格描述')),
                ('UCL', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='上限值')),
                ('CL', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='中心值')),
                ('LCL', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='下限值')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updatename', models.CharField(blank=True, max_length=40, null=True, verbose_name='添加者')),
            ],
            options={
                'verbose_name': '210产品参数',
                'verbose_name_plural': '210产品参数',
            },
        ),
        migrations.CreateModel(
            name='itempcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40, verbose_name='料号')),
                ('step', models.SmallIntegerField(default=1, null=True, verbose_name='作业步骤')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updatename', models.CharField(blank=True, max_length=40, verbose_name='添加者')),
            ],
            options={
                'verbose_name': '211产品流程',
                'verbose_name_plural': '211产品流程',
                'ordering': ['item', 'step'],
            },
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('opcode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='工作编码')),
                ('opname', models.CharField(max_length=80, verbose_name='工作中心')),
                ('category', models.CharField(blank=True, choices=[('1', '虚设'), ('2', '标准'), ('3', '专属')], max_length=40, null=True, verbose_name='类别')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('PCE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operationpce', to=settings.AUTH_USER_MODEL, verbose_name='制程工程师')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 1), ('category', 2), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='p_pdm.operation', verbose_name='父级站')),
            ],
            options={
                'verbose_name': '205工作中心',
                'verbose_name_plural': '205工作中心',
                'ordering': ['category', 'opcode'],
            },
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('parameter', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='参数名称')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数描述')),
                ('pmproperty', models.CharField(choices=[('1', '通用参数'), ('2', '标准参数')], default=1, help_text='1:通用参数，如进出烘箱时间；2:标准参数，如产品测试值。', max_length=20, null=True, verbose_name='参数特征')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('process', models.ForeignKey(blank=True, limit_choices_to=models.Q(category='2'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter', to='p_pdm.operation', verbose_name='所属制程')),
            ],
            options={
                'verbose_name': '209制程参数',
                'verbose_name_plural': '209制程参数',
            },
        ),
        migrations.CreateModel(
            name='pcode',
            fields=[
                ('pcode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='作业代码')),
                ('pname', models.CharField(max_length=80, verbose_name='作业名称')),
                ('labor', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='作业工时(单位：秒)')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operation', models.ForeignKey(blank=True, limit_choices_to=models.Q(category='2'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcode', to='p_pdm.operation', verbose_name='所属工作中心')),
            ],
            options={
                'verbose_name': '207作业制程',
                'verbose_name_plural': '207作业制程',
            },
        ),
        migrations.CreateModel(
            name='pcoderev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=40, verbose_name='作业代码')),
                ('pname', models.CharField(max_length=40, verbose_name='作业名称')),
                ('labor', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='作业工时(单位：秒)')),
                ('changes', models.TextField(null=True, verbose_name='修订原因')),
                ('states', models.SmallIntegerField(null=True, verbose_name='标准版次')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修订时间')),
                ('updatename', models.CharField(blank=True, max_length=40, null=True, verbose_name='修订者')),
            ],
            options={
                'verbose_name': '208修订记录',
                'verbose_name_plural': '208修订记录',
                'ordering': ['pcode', 'states'],
            },
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('process', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='作业类型')),
                ('prodesc', models.TextField(null=True, verbose_name='分类说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '206作业类型',
                'verbose_name_plural': '206作业类型',
            },
        ),
        migrations.CreateModel(
            name='productgroup',
            fields=[
                ('groupcode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='产品族编码')),
                ('groupname', models.CharField(max_length=80, unique=True, verbose_name='产品族名称')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('PM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productgrouppm', to=settings.AUTH_USER_MODEL, verbose_name='产品经理')),
            ],
            options={
                'verbose_name': '201产品族',
                'verbose_name_plural': '201产品族',
                'ordering': ['groupcode', 'PM'],
            },
        ),
        migrations.CreateModel(
            name='productline',
            fields=[
                ('PL', models.OneToOneField(limit_choices_to=models.Q(('category', 'P'), ('category', 'C'), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='productline', serialize=False, to='p_admin.department', verbose_name='产线')),
                ('ERP', models.CharField(blank=True, max_length=40, null=True, verbose_name='财务代码')),
                ('ADM', models.CharField(blank=True, max_length=40, null=True, verbose_name='行政代码')),
                ('SFM', models.CharField(blank=True, max_length=40, null=True, verbose_name='生产代码')),
                ('APS', models.CharField(blank=True, max_length=40, null=True, verbose_name='计划代码')),
                ('OPM', models.CharField(blank=True, max_length=40, null=True, verbose_name='绩效代码')),
                ('WMS', models.CharField(blank=True, max_length=40, null=True, verbose_name='仓储代码')),
                ('SCM', models.CharField(blank=True, max_length=40, null=True, verbose_name='采购代码')),
                ('PDM', models.CharField(blank=True, max_length=40, null=True, verbose_name='工程代码')),
                ('MES', models.CharField(blank=True, max_length=40, null=True, verbose_name='系统代码')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operation', models.ManyToManyField(blank=True, limit_choices_to=models.Q(category='2'), null=True, to='p_pdm.operation', verbose_name='工作中心')),
            ],
            options={
                'verbose_name': '204产品线',
                'verbose_name_plural': '204产品线',
                'ordering': ['PL'],
            },
        ),
        migrations.CreateModel(
            name='producttree',
            fields=[
                ('productcode', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='产品群编码')),
                ('productname', models.CharField(max_length=80, unique=True, verbose_name='产品群名称')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('PDE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producttreepde', to=settings.AUTH_USER_MODEL, verbose_name='产品工程师')),
                ('PG', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pgs', to='p_pdm.productgroup', verbose_name='产品族')),
                ('item', models.ManyToManyField(blank=True, null=True, related_name='productreeitem', to='p_pdm.item', verbose_name='产品号(群)')),
                ('operation', models.ManyToManyField(blank=True, limit_choices_to=models.Q(category='2'), null=True, related_name='productreeoperation', to='p_pdm.operation', verbose_name='工作中心')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='p_pdm.producttree', verbose_name='父级群')),
                ('process', models.ManyToManyField(blank=True, limit_choices_to=models.Q(category='3'), null=True, related_name='productreepcode', to='p_pdm.operation', verbose_name='作业制程')),
            ],
            options={
                'verbose_name': '202产品群',
                'verbose_name_plural': '202产品群',
                'ordering': ['productcode'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pcoderev',
            unique_together={('pcode', 'updatetime')},
        ),
        migrations.AddField(
            model_name='itempcode',
            name='pcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itempocdepcode2', to='p_pdm.pcode', verbose_name='作业'),
        ),
        migrations.AddField(
            model_name='itemparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemparameter', to='p_pdm.parameter', verbose_name='参数名称'),
        ),
        migrations.AlterUniqueTogether(
            name='itembom',
            unique_together={('item', 'component')},
        ),
        migrations.AddField(
            model_name='item',
            name='productgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itempgs', to='p_pdm.producttree', verbose_name='产品群'),
        ),
        migrations.AlterUniqueTogether(
            name='itempcode',
            unique_together={('item', 'pcode')},
        ),
        migrations.AlterUniqueTogether(
            name='itemparameter',
            unique_together={('item', 'parameter')},
        ),
    ]
