# Generated by Django 2.0.4 on 2018-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operationpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opdesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operationpro', to='p_pdm.operation', verbose_name='工作中心')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operationpar', to='p_pdm.process', verbose_name='作业参数')),
            ],
            options={
                'verbose_name': '2051工作参数',
                'verbose_name_plural': '2051工作参数',
            },
        ),
        migrations.AlterUniqueTogether(
            name='operationpro',
            unique_together={('operation', 'process')},
        ),
    ]
