# Generated by Django 2.0.4 on 2018-07-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0002_auto_20180710_1045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationpro',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='operationpro',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationpro',
            name='process',
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': '206作业参数', 'verbose_name_plural': '206作业参数'},
        ),
        migrations.AddField(
            model_name='operation',
            name='process',
            field=models.ManyToManyField(blank=True, null=True, to='p_pdm.process', verbose_name='作业参数'),
        ),
        migrations.DeleteModel(
            name='operationpro',
        ),
    ]
