# Generated by Django 2.0.4 on 2018-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0003_auto_20180710_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': '206工作参数', 'verbose_name_plural': '206工作参数'},
        ),
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='工作参数'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prodesc',
            field=models.TextField(null=True, verbose_name='参数说明'),
        ),
    ]
