# Generated by Django 2.0.4 on 2018-07-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0005_auto_20180713_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemparameter',
            options={'verbose_name': '产品参数', 'verbose_name_plural': '产品参数'},
        ),
        migrations.AlterModelOptions(
            name='itempcode',
            options={'ordering': ['item', 'step'], 'verbose_name': '209产品途程', 'verbose_name_plural': '209产品途程'},
        ),
        migrations.AlterModelOptions(
            name='itempcodespec',
            options={'verbose_name': '211制程规格', 'verbose_name_plural': '211制程规格'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': '210制程参数', 'verbose_name_plural': '210制程参数'},
        ),
        migrations.AlterField(
            model_name='item',
            name='itemgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemgroups', to='p_pdm.item', verbose_name='共用途程'),
        ),
    ]
