# Generated by Django 2.0.4 on 2018-07-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0006_auto_20180713_2032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemparameter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemparameter',
            name='parameter',
        ),
        migrations.AlterModelOptions(
            name='itempcodespec',
            options={'verbose_name': '211途程参数规格', 'verbose_name_plural': '211途程参数规格'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': '210途程参数', 'verbose_name_plural': '210途程参数'},
        ),
        migrations.AlterModelOptions(
            name='pcode',
            options={'verbose_name': '207制程标准', 'verbose_name_plural': '207制程标准'},
        ),
        migrations.AlterModelOptions(
            name='pcoderev',
            options={'ordering': ['pcode', 'states'], 'verbose_name': '208标准修订', 'verbose_name_plural': '208标准修订'},
        ),
        migrations.DeleteModel(
            name='itemparameter',
        ),
    ]
