# Generated by Django 2.0.4 on 2018-07-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0007_auto_20180714_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['productgroup', 'item'], 'verbose_name': '203产品码', 'verbose_name_plural': '203产品码'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='产品码'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemdesc',
            field=models.TextField(blank=True, null=True, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemspec',
            field=models.TextField(blank=True, null=True, verbose_name='产品规格'),
        ),
        migrations.AlterField(
            model_name='itempcodespec',
            name='CL',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='中心值'),
        ),
        migrations.AlterField(
            model_name='itempcodespec',
            name='LCL',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='下限值'),
        ),
        migrations.AlterField(
            model_name='itempcodespec',
            name='UCL',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='上限值'),
        ),
        migrations.AlterField(
            model_name='itempcodespec',
            name='spec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='单位'),
        ),
    ]
