# Generated by Django 2.0.4 on 2018-07-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_pdm', '0008_auto_20180714_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempcodespec',
            options={'verbose_name': '211途程参数', 'verbose_name_plural': '211途程参数'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': '210参数定义', 'verbose_name_plural': '210参数定义'},
        ),
        migrations.AddField(
            model_name='item',
            name='route',
            field=models.ManyToManyField(blank=True, null=True, through='p_pdm.itempcode', to='p_pdm.pcode', verbose_name='途程'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemgroups', to='p_pdm.item', verbose_name='途程'),
        ),
        migrations.AlterField(
            model_name='itempcode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itempocdepcode1', to='p_pdm.item', verbose_name='料号'),
        ),
    ]
