# Generated by Django 2.0.4 on 2018-06-22 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0001_initial'),
        ('runtime', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to='workflow.Activity', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to='runtime.ProcessInstance', verbose_name='流程'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='others_workitems_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_workitem_others_workitems_from_+', to='runtime.WorkItem', verbose_name='关联表单'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='pull_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='pull_workitems', to='auth.Group', verbose_name='角色推动'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='push_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='push_workitems', to='auth.Group', verbose_name='角色拉动'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='workitem_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems_to', to='runtime.WorkItem', verbose_name='工作表单'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='数据模型'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instances', to='workflow.Process', verbose_name='流程'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instances', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='event',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='runtime.WorkItem', verbose_name='工作'),
        ),
    ]
