# Generated by Django 2.0.4 on 2018-07-09 00:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(choices=[('standard', '标准'), ('dummy', '虚拟'), ('subflow', '子流程')], default='standard', max_length=10, verbose_name='类型')),
                ('pushapp_param', models.CharField(blank=True, help_text="parameters dictionary; example: {'username':'john'}", max_length=100, null=True, verbose_name='推送应用参数')),
                ('app_param', models.CharField(blank=True, help_text='parameters dictionary', max_length=100, null=True, verbose_name='过程应用参数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('autostart', models.BooleanField(default=False, verbose_name='自动开始')),
                ('autofinish', models.BooleanField(default=True, verbose_name='自动结束')),
                ('join_mode', models.CharField(choices=[('and', '与'), ('xor', '或')], default='xor', max_length=3, verbose_name='合并模式')),
                ('split_mode', models.CharField(choices=[('and', '与'), ('xor', '或')], default='and', max_length=3, verbose_name='分开模式')),
            ],
            options={
                'verbose_name': '1105过程定义',
                'verbose_name_plural': '1105过程定义',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='relative to prefix in settings.WF_APPS_PREFIX', max_length=255, unique=True, verbose_name='应用路径')),
                ('suffix', models.CharField(blank=True, choices=[('w', '工作.id'), ('i', '程序.id'), ('o', '对像.id')], default='w', help_text='http://[host]/[settings.WF_APPS_PREFIX/][url]/[suffix]', max_length=1, null=True, verbose_name='应用类型')),
            ],
            options={
                'verbose_name': '1107应用定义',
                'verbose_name_plural': '1107应用定义',
            },
        ),
        migrations.CreateModel(
            name='DefaultAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, editable=False, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '1101应用',
                'verbose_name_plural': '1101应用',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='事件')),
            ],
            options={
                'verbose_name': '1113事件',
                'verbose_name_plural': '1113事件',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '1115',
                'verbose_name_plural': '1115',
            },
        ),
        migrations.CreateModel(
            name='graphicsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '1114事件图形',
                'verbose_name_plural': '1114事件图形',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标分类')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '1103图标',
                'verbose_name_plural': '1103图标',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='图形分类')),
                ('file', models.ImageField(upload_to='images', verbose_name='图形文件')),
            ],
            options={
                'verbose_name': '1102图形',
                'verbose_name_plural': '1102图形',
            },
        ),
        migrations.CreateModel(
            name='ImageButton',
            fields=[
                ('action', models.SlugField(primary_key=True, serialize=False, verbose_name='动作')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p_wkf.Icon', verbose_name='图标')),
            ],
            options={
                'verbose_name': '1104按键',
                'verbose_name_plural': '1104按键',
            },
        ),
        migrations.CreateModel(
            name='MetaGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_attr', models.CharField(default='parent', max_length=50)),
                ('children_attr', models.CharField(default='children', max_length=50)),
                ('position_method', models.CharField(default='position', max_length=50)),
                ('zorder_method', models.CharField(default='zorder', max_length=50)),
                ('moveable_method', models.CharField(default='is_moveable', max_length=50)),
                ('content_type', models.ManyToManyField(to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='p_wkf.MetaGraph')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p_wkf.Graph')),
            ],
            options={
                'verbose_name': '1116',
                'verbose_name_plural': '1116',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否可用')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('title', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(verbose_name='说明')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('begin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bprocess', to='p_wkf.Activity', verbose_name='开始过程')),
                ('end', models.ForeignKey(blank=True, help_text='a default end activity will be created if blank', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eprocess', to='p_wkf.Activity', verbose_name='结束过程')),
            ],
            options={
                'verbose_name': '1106流程定义',
                'verbose_name_plural': '1106流程定义',
                'permissions': (('can_instantiate', 'Can instantiate'), ('can_browse', 'Can browse')),
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='模型名称')),
                ('creationTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('initiated', '发起'), ('running', '进程中'), ('active', '有效'), ('complete', '完成'), ('terminated', '终止'), ('suspended', '暂停')], default='initiated', max_length=10, verbose_name='当前状态')),
                ('old_status', models.CharField(blank=True, choices=[('initiated', '发起'), ('running', '进程中'), ('active', '有效'), ('complete', '完成'), ('terminated', '终止'), ('suspended', '暂停')], max_length=10, null=True, verbose_name='原始状态')),
                ('condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='条件')),
                ('object_id', models.PositiveIntegerField(verbose_name='正整数序号')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='数据模型')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instances', to='p_wkf.Process', verbose_name='流程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instances', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '1111流程模型',
                'verbose_name_plural': '1111流程模型',
            },
        ),
        migrations.CreateModel(
            name='PushApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '1108推送应用',
                'verbose_name_plural': '1108推送应用',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('condition', models.CharField(blank=True, help_text='ex: instance.condition=="OK" | OK', max_length=200, null=True, verbose_name='过程条件')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='过程说明')),
                ('precondition', models.SlugField(blank=True, help_text='object method that return True if transition is posible', null=True, verbose_name='预定条件')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_inputs', to='p_wkf.Activity', verbose_name='过程输入')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_outputs', to='p_wkf.Activity', verbose_name='过程输出')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transitions', to='p_wkf.Process', verbose_name='流程')),
            ],
            options={
                'verbose_name': '1109过程转换',
                'verbose_name_plural': '1109过程转换',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_host', models.CharField(default='http://192.168.1.3:83/profile/', max_length=100, verbose_name='个人网址')),
                ('notified', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('last_notif', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后通知时间')),
                ('nb_wi_notif', models.IntegerField(default=1, help_text='notification if the number of items waiting is reached', verbose_name='消息数')),
                ('notif_delay', models.IntegerField(default=1, help_text='in days', verbose_name='延后通知')),
                ('urgent_priority', models.IntegerField(default=5, help_text='a mail notification is sent when an item has at least this priority level', verbose_name='优先级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '1110用户消息设置',
                'verbose_name_plural': '1110用户消息设置',
            },
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField(default=0)),
                ('h', models.PositiveSmallIntegerField(default=0)),
                ('need_update', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('z', models.PositiveSmallIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p_wkf.Graph')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='p_wkf.Image')),
            ],
            options={
                'verbose_name': '1117流程可视',
                'verbose_name_plural': '1117流程可视',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级别')),
                ('status', models.CharField(choices=[('blocked', '锁定'), ('inactive', '无效'), ('active', '有效'), ('suspended', '暂停'), ('fallout', '后续'), ('complete', '完成')], default='inactive', max_length=10, verbose_name='状态')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to='p_wkf.Activity', verbose_name='活动')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to='p_wkf.ProcessInstance', verbose_name='流程')),
                ('others_workitems_from', models.ManyToManyField(blank=True, null=True, related_name='_workitem_others_workitems_from_+', to='p_wkf.WorkItem', verbose_name='关联表单')),
                ('pull_roles', models.ManyToManyField(blank=True, null=True, related_name='pull_workitems', to='auth.Group', verbose_name='角色推动')),
                ('push_roles', models.ManyToManyField(blank=True, null=True, related_name='push_workitems', to='auth.Group', verbose_name='角色拉动')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('workitem_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workitems_to', to='p_wkf.WorkItem', verbose_name='工作表单')),
            ],
            options={
                'verbose_name': '1112工作项目',
                'verbose_name_plural': '1112工作项目',
                'permissions': (('can_change_priority', 'Can change priority'),),
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bg_graphes', to='p_wkf.Visual'),
        ),
        migrations.AddField(
            model_name='graph',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='p_wkf.Graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='p_wkf.WorkItem', verbose_name='工作'),
        ),
        migrations.AddField(
            model_name='activity',
            name='application',
            field=models.ForeignKey(blank=True, help_text='leave it blank for prototyping the process without coding', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='p_wkf.Application', verbose_name='过程应用'),
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='p_wkf.Process', verbose_name='流程'),
        ),
        migrations.AddField(
            model_name='activity',
            name='push_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='push_activities', to='p_wkf.PushApplication', verbose_name='推送应用'),
        ),
        migrations.AddField(
            model_name='activity',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='auth.Group', verbose_name='过程角色'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_activities', to='p_wkf.Process', verbose_name='子流程'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('title', 'process')},
        ),
    ]
