# Generated by Django 2.0.4 on 2018-06-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, editable=False, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Simulation object',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标分类')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '图标',
                'verbose_name_plural': '图标',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='图形分类')),
                ('file', models.ImageField(upload_to='images', verbose_name='图形文件')),
            ],
            options={
                'verbose_name': '图形',
                'verbose_name_plural': '图形',
            },
        ),
        migrations.CreateModel(
            name='ImageButton',
            fields=[
                ('action', models.SlugField(primary_key=True, serialize=False, verbose_name='动作')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptools.Icon', verbose_name='图标')),
            ],
            options={
                'verbose_name': '按键',
                'verbose_name_plural': '按键',
            },
        ),
    ]
