# Generated by Django 2.0.4 on 2018-07-09 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=80, verbose_name='模版')),
                ('item', models.CharField(blank=True, max_length=120, null=True, verbose_name='项目')),
                ('Xaxis', models.SmallIntegerField(verbose_name='Rows行座标')),
                ('Yaxis', models.SmallIntegerField(verbose_name='Columns列座标')),
                ('TS01', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数01')),
                ('TS02', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数02')),
                ('TS03', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数03')),
                ('TS04', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数04')),
                ('TS05', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数05')),
                ('TS06', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数06')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '1001模版',
                'verbose_name_plural': '1001模版',
            },
        ),
        migrations.CreateModel(
            name='TestRowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=80, verbose_name='序号')),
                ('Channel', models.CharField(blank=True, max_length=80, null=True, verbose_name='通道')),
                ('Parameter', models.CharField(blank=True, max_length=80, null=True, verbose_name='参数')),
                ('Value', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='数值')),
                ('Judge', models.BooleanField(default=True, verbose_name='判定结果')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('PA01', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA01')),
                ('PA02', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA02')),
                ('PA03', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA03')),
                ('PA04', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA04')),
                ('PA05', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA05')),
                ('PA06', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='PA06')),
                ('PB01', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB01')),
                ('PB02', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB02')),
                ('PB03', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB03')),
                ('PB04', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB04')),
                ('PB05', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB05')),
                ('PB06', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='PB06')),
                ('PC01', models.CharField(max_length=80, null=True, verbose_name='PC01')),
                ('PC02', models.CharField(max_length=80, null=True, verbose_name='PC02')),
                ('PC03', models.CharField(max_length=80, null=True, verbose_name='PC03')),
                ('PC04', models.CharField(max_length=80, null=True, verbose_name='PC04')),
                ('PC05', models.CharField(max_length=80, null=True, verbose_name='PC05')),
                ('PC06', models.CharField(max_length=80, null=True, verbose_name='PC06')),
            ],
            options={
                'verbose_name': '1003PLC测试数据',
                'verbose_name_plural': '1003测试数据',
            },
        ),
        migrations.CreateModel(
            name='TestSN',
            fields=[
                ('sn', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='序号')),
                ('product', models.CharField(blank=True, max_length=120, null=True, verbose_name='产品')),
                ('po', models.CharField(blank=True, max_length=80, null=True, verbose_name='订单')),
                ('poid', models.CharField(blank=True, max_length=40, null=True, verbose_name='订单项次')),
                ('item', models.CharField(blank=True, max_length=80, null=True, verbose_name='料号')),
                ('states', models.SmallIntegerField(default='1', help_text='1:正常，-1：不良, 99：完工，0：删除', verbose_name='状态码')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('PC01', models.CharField(max_length=80, null=True, verbose_name='PC01')),
                ('PC02', models.CharField(max_length=80, null=True, verbose_name='PC02')),
                ('PC03', models.CharField(max_length=80, null=True, verbose_name='PC03')),
                ('PC04', models.CharField(max_length=80, null=True, verbose_name='PC04')),
                ('PC05', models.CharField(max_length=80, null=True, verbose_name='PC05')),
                ('PC06', models.CharField(max_length=80, null=True, verbose_name='PC06')),
            ],
            options={
                'verbose_name': '1002测试序号',
                'verbose_name_plural': '1002测试序号',
            },
        ),
    ]
