# Generated by Django 2.0.4 on 2018-07-20 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_aps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='出货通知单号')),
                ('po', models.CharField(max_length=40, verbose_name='订单号码')),
                ('poid', models.CharField(max_length=40, verbose_name='项次')),
                ('box', models.CharField(default='1', max_length=40, verbose_name='外箱号')),
                ('boxid', models.CharField(default='1', max_length=40, null=True, verbose_name='内箱号')),
                ('pn', models.CharField(max_length=40, verbose_name='料号')),
                ('qty', models.SmallIntegerField(default=100, verbose_name='数量')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '407装箱清单',
                'verbose_name_plural': '407装箱清单',
            },
        ),
        migrations.CreateModel(
            name='packinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40, verbose_name='出货通知单号')),
                ('packingdate', models.DateField(default=django.utils.timezone.now, verbose_name='装箱日期')),
                ('customer', models.CharField(max_length=40, verbose_name='客户代码')),
                ('box', models.CharField(max_length=40, verbose_name='箱号')),
                ('po', models.CharField(max_length=40, verbose_name='订单号码')),
                ('poid', models.CharField(max_length=40, verbose_name='项次')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='产品规格')),
                ('qty', models.SmallIntegerField(default=100, verbose_name='装箱数量')),
                ('packingmethod', models.CharField(blank=True, default='自封箱', max_length=60, null=True, verbose_name='包装方式')),
                ('boxsize', models.CharField(blank=True, default='54*54*30', max_length=60, null=True, verbose_name='外箱尺寸')),
                ('netweight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='净重')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='毛重')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '406装箱清单',
                'verbose_name_plural': '406装箱清单',
            },
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40, verbose_name='出货通知单号')),
                ('shippingdate', models.DateField(default=django.utils.timezone.now, verbose_name='出货日期')),
                ('customer', models.CharField(max_length=40, verbose_name='客户代码')),
                ('po', models.CharField(max_length=40, verbose_name='订单号码')),
                ('poid', models.CharField(max_length=40, verbose_name='项次')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品规格')),
                ('qty', models.SmallIntegerField(default=1, verbose_name='出货数量')),
                ('shippingtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='出货时间')),
                ('shippingmethod', models.CharField(blank=True, max_length=60, null=True, verbose_name='货运方式')),
                ('confirm', models.CharField(blank=True, max_length=200, null=True, verbose_name='实际出货')),
                ('status', models.CharField(blank=True, choices=[('Open', '准备出货'), ('Close', '出货完结'), ('Delay', '延迟出货'), ('Change', '变更数量'), ('Cancel', '取消出货')], default='Open', max_length=40, null=True, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updatename', models.CharField(blank=True, max_length=40, verbose_name='添加者')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '405出货通知',
                'verbose_name_plural': '405出货通知',
            },
        ),
        migrations.AlterModelOptions(
            name='mps',
            options={'ordering': ['pdate', 'po', 'poid'], 'verbose_name': '403主排程', 'verbose_name_plural': '403主排程'},
        ),
        migrations.AlterUniqueTogether(
            name='packinglist',
            unique_together={('item', 'po', 'poid', 'box')},
        ),
        migrations.AlterUniqueTogether(
            name='packing',
            unique_together={('item', 'po', 'poid', 'box', 'boxid')},
        ),
    ]
